import "./globals.css";
import Navbar from "./components/Navbar"
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased p-2 lg:p-8 lg:m-6 flex flex-col gap-4`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
