import "./globals.css";
import Navbar from "./components/Navbar"
import type { Metadata } from "next";

import { Playfair_Display, DM_Sans } from 'next/font/google'

const playfair = Playfair_Display({ 
  subsets: ['latin'], 
  variable: '--font-playfair' 
})

const dmSans = DM_Sans({ 
  subsets: ['latin'], 
  variable: '--font-sans' 
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased p-2 lg:p-6 flex flex-col gap-4 overflow-x-hidden`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
